### ISSUE TITLE
Please fix your infinite drives bug, Cannot Delete It!!!

### ISSUE THREAD

**Issue by Ferynix** [jaysalvat/image2css#2]
Im not sure why you decided to add like 30 drives to it, but now I had to substrate the project into a new drive just to delete it because your 30 drives were somehow taking up 2.5 FRICKING GIGABYTES BY SIMPLY HAVING NAMES THAT ARE TOO LONG.... I had to make and delete drives off my pc just to get rid of it... I mean comon. I almost thought it was a virus, then I realised it was just someone who decided making 30+ directories would be a good idea. :/

**Comment by jaysalvat** [comment]
Hello. 
What are you talking about?
Can you give me some hints to how to reproduce it? Code example?

**Comment by jaysalvat** [comment]
Please reopen with code example.
